services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-docker
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: billing_system2
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  spring-app:
    image: billing-system
    container_name: billings-app
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/billing_system2?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8022:10000"
    networks:
      - app-network
    restart: on-failure

volumes:
  mysql-data:
    driver: local

networks:
  app-network:
    driver: bridge